runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 20
env_variables:
  NODE_ENV: 'production'
  API_BASE_URL: 'http://34.85.87.212:3000'
  GCLOUD_STORAGE_BUCKET: 'inustagram-images'
